# Generated by Django 3.2.3 on 2021-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
